import type { Metadata } from 'next';
import { Newsreader } from 'next/font/google';
import './globals.css';

const newsReader = Newsreader();

export const metadata: Metadata = {
	title: 'Facility Web Experience',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={newsReader.className}>
			<head></head>
			<body className={`antialiased`}>{children}</body>
		</html>
	);
}
